jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: build -target BuildServer
    env:
      MYGET_API_KEY: $(MYGET_API_KEY)
      WYAM_CERTPASS: $(WYAM_CERTPASS)
      SIGNTOOL: C:/Program Files (x86)/Microsoft SDKs/Windows/v7.1A/Bin/SignTool.exe
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
- job: Linux
  pool:
    vmImage: 'ubuntu 16.04'
  steps:
  - script: pwsh ./build.ps1 -target BuildServer
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'      
- job: Mac
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: pwsh ./build.ps1 -target BuildServer
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'